### ISSUE TITLE
Datacite schema

### ISSUE THREAD

**Issue by lorenzino** [kata-csc/ckanext-oaipmh#1]
Dear all, 
I've read the documentation and realized that supported metadata schemas are oai_dc (Dublin Core), CMDI (Component MetaData Infrastructure). Are you planning to support also the datacite schema?

Cheers,
Lorenzino

**Comment by razz0** [comment]
Yes, we are planning to support datacite schema. We will be looking into this in the near future, but it is uncertain when a harvester for this will actually be implemented.
